### ISSUE TITLE
Adding location parameter to filtered-stream query

### ISSUE THREAD

**Issue by dhowe** [twitterdev/Twitter-API-v2-sample-code#1]
Example code is super helpful as I  migrate my app to the v2 api, but I can't find any documentation on how to add location tags to a query (specifically for countries, though geo-bounding-boxes, as in v1, would also work)

**Comment by andypiper** [comment]
Thanks for asking about this. In the [migration documentation](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/migrate/standard-to-twitter-api-v2), we've mentioned that "We have not released location-based operators for Twitter API v2 yet". At this stage in the early access process, there's no direct equivalent.

**Comment by dhowe** [comment]
Thanks. Just curious as the page states there is only 60 days to migrate, and I'm not sure when those days began

**Comment by andypiper** [comment]
60 days to migrate between Labs v1 stream and the new v2 endpoint, correct (from the launch on August 12th); v1.1 will have a longer migration window. Thanks for calling this out, though - we can make this more clear.

**Comment by dhowe** [comment]
understood, but if we have a v1 app that relies on location data, what is the expected action in terms of migration ?

**Comment by andypiper** [comment]
If you currently have a Labs v1 app that is using this stream, you may need to temporarily fall back to v1.1 stream for the location feature; we’ll share more on location availability in operators when we can. In the meantime, per the other issue, I’m going to close this in favour of [this thread on our developer forums](https://twittercommunity.com/t/twitter-api-v2-filtered-stream-rules/141278); thank you for your understanding as this is not an issue with the sample code, but rather with the features currently in the v2 API.

**Comment by Qdamwowo** [comment]
Woow
