### ISSUE TITLE
How to get full 'text' for tweets using filtered streams

### ISSUE THREAD

**Issue by dhowe** [twitterdev/Twitter-API-v2-sample-code#2]
This field currently seems to be truncated (with ellipses) for longer tweets

**Comment by andypiper** [comment]
Can you provide any Tweet IDs where this is the case?
Are they Retweets?

Are you using any other parameters beyond the ones provided in the sample code, to get additional fields or expansions?

**Comment by dhowe** [comment]
Thanks for the reply. So they do seem to be retweets (example: #1296315656623681537), though I was attempting to explicitly eliminate retweets.

This is the rule and URL (used w' the example code):
 ```
const rules = [  { 'value': '"global warming" OR "climate change" -is:retweet', 'tag': 'ecb1' } ];
const streamURL = 'https://api.twitter.com/2/tweets/search/stream?expansions=author_id&user.fields=location';
```

**Comment by andypiper** [comment]
Thanks for confirming, will need to check on the expectations here.

**Comment by dhowe** [comment]
Do let me know if there is some other way I should be filtering out retweets...

**Comment by andypiper** [comment]
I’m going to close this issue in favour of [this thread on our developer forums](https://twittercommunity.com/t/will-extended-tweet-text-be-available-in-sample-stream-and-tweet-lookup/141073), which is a better location to have a more wide-ranging conversation on the API in general. Thank you so much.
