### ISSUE TITLE
Recent search not working in browser. I am constantly getting CORS error

### ISSUE THREAD

**Issue by bhavesh2799** [twitterdev/Twitter-API-v2-sample-code#32]
`getTweets(){
   
  var myHeaders = new HttpHeaders();
  myHeaders.append("Authorization", "Bearer "+this.token);
  // myHeaders.append("Cookie", "guest_id=v1%3A161908241149107957; personalization_id=\"v1_ejJZ4HGUOXH10orpNKx4xQ==\"");
  
  var requestOptions = {
    method: 'GET',
  
    headers: myHeaders,
    redirect: 'follow'
  };
  
  fetch("https://api.twitter.com/1.1/search/tweets.json?q==ECONOMICTIMES&max_results=10&tweet.fields=author_id,created_at,entities,geo,in_reply_to_user_id,lang,possibly_sensitive,referenced_tweets,source", requestOptions)
    .then(response => response.text())
    .then(result => console.log(result))
    .catch(error => console.log('error', error));
}
`

**Comment by andypiper** [comment]
This is not related to the v2 API (you have /1.1/ in the URL) so the fields and expansions will not work. Also, Twitter’s API does not support CORS.

I recommend that you use twittercommunity.com for follow-up questions since this does not relate to these samples.

**Comment by SHIVANGISINGH1** [comment]
I am also facing CORS error how do I solve it.

**Comment by andypiper** [comment]
The Twitter API does not support CORS so you will have to call it from a server-side application rather than directly from JavaScript in the browser.

**Comment by SHIVANGISINGH1** [comment]
> The Twitter API does not support CORS so you will have to call it from a server-side application rather than directly from JavaScript in the browser.

Okay, I'll try on node thanks :)
