### ISSUE TITLE
400 Bad Request upon using next token

### ISSUE THREAD

**Issue by Diana0604** [twitterdev/Twitter-API-v2-sample-code#40]
I am using the code in the github example page to [check followers with node.js](https://github.com/twitterdev/Twitter-API-v2-sample-code/blob/master/Follows-Lookup/followers_lookup.js). The command works well, except when the number of followers exceeds the max.results (1000). When this happens, the code resends the request using the nextToken parameter. But the response is a 400 error (Bad Request).

After prodding through the documentation I discovered the proper parameter is `pagination_token`, instead of `next_token.` So, in the code, **line 53** should change to: 
`params.pagination_token = nextToken;`

(Info from: [quickstart followers documentation](https://developer.twitter.com/en/docs/twitter-api/users/follows/quick-start/follows-lookup) )

**Comment by andypiper** [comment]
Thank you!
