### ISSUE TITLE
Cannot get rules (HTTP 401)

### ISSUE THREAD

**Issue by RPBTwisted** [twitterdev/Twitter-API-v2-sample-code#72]
The bug occurs when using the code example for Filtered-Stream. I have set the bearer token through the console as it mentions but I still receive a 401 which would hint towards me not being authorized. I don't know if I have done something wrong regarding the setting of the token, but I did this through the console in VSCode. 

The actual error message I received was the one below. I'm not fabulous with Python or the API so I'm a little stuck.

`Exception has occurred: Exception
Cannot get rules (HTTP 401): {"title":"Unauthorized","detail":"Unauthorized","type":"about:blank","status":401}
  File "C:\Users\Rhys\OneDrive\Documents\TwitterCrawl.py", line 25, in get_rules
    raise Exception(
  File "C:\Users\Rhys\OneDrive\Documents\TwitterCrawl.py", line 89, in main
    rules = get_rules()
  File "C:\Users\Rhys\OneDrive\Documents\TwitterCrawl.py", line 96, in <module>
    main()`

**Comment by bhushan-borole** [comment]
@RPBTwisted Did you find the solution to this?
