### ISSUE TITLE
Provide reconnection examples for streams

### ISSUE THREAD

**Issue by andypiper** [twitterdev/Twitter-API-v2-sample-code#9]
per this forum conversation (and others)

https://twittercommunity.com/t/filtered-stream-reconnect-code-sample/144821

It would be helpful to provide some form of sample that discusses or implements reconnections.

**Comment by burtomaps** [comment]
Hi, this is a very nice thing, but my account is still restricted.  I need to open my account in order to use its features

My name  In Twitter @ burtomaps

**Comment by andypiper** [comment]
@burtomaps we cannot support you with account issues on GitHub code samples; please use help.twitter.com instead. Thank you.

**Comment by mr-devs** [comment]
Thanks for opening this @andypiper! Any chance we'll see this in the (relatively) near future? 😄 Hoping to include some of this functionality in a [Twitter V2 python package](https://github.com/osome-iu/osometweet) (aimed at academics) we are in the process of developing.
